### PR TITLE
Add aarch64 create-env image

### PR DESCRIPTION
**Pull request by mbargull**
### Changed

- Add linux-aarch64 image; bioconda/create-env is now a multiplatform manifest.

- Change to a simple "major.minor" version scheme and offer mutable "major" tag.

- Drop defaults channel from included config.

- Use Miniforge installer to build this image.

- Rebuilt on the latest base image with Debian 12.2 / BusyBox 1.36.1.

- Do not install findutils, sed if provided by the base image (as is currently).

### CODE REVIEW

**Review by martin-g — APPROVED** [review]
LGTM!

**Comment by mbargull** [comment]
Thanks for taking a look!
There were yet again some annoying issues with manifest vs image handling, Buildah and Podman command differences, and older Buildah/Podman versions with different behavior/missing features on the CI.
This is finally properly testing for all architectures and ready to push.

**Comment by mjsteinbaugh** [comment]
@mbargull @martin-g Are we ready to roll with working on build recipes for aarch64? Happy to help contribute with that

**Comment by mbargull** [comment]
> Happy to help contribute with that

That's great, thank you!

> Are we ready to roll with working on build recipes for aarch64?

I'm not entirely caught up on everything that is still needed, so I can't say for certain.
In https://github.com/bioconda/bioconda-recipes/pull/40550 work is being done on getting the CI for aarch64 setup.
As I gathered, @martin-g and @Yikun have already looked into building recipes locally. If you'd like to have a look at some recipes before `bioconda-recipes`' CI is set up, it probably makes sense to look into their work.

**Comment by martin-g** [comment]
@mjsteinbaugh Please take a look at https://github.com/bioconda/bioconda-recipes/issues/23454#issuecomment-1770590292 
This is what we use to build custom recipes at the moment! 
Save it as `build-recipes.sh` and execute it on Linux aarch64 machine as: 
``` 
cd path/to/bioconda-recipes/
build-recipes.sh ./recipes msa
```

**Pull request merged**
