### PR TITLE
Extend debian base image with libegl1 and libopengl0

### PR DESCRIPTION
**Pull request by mvdbeek**
This is required to run the bandage biocontainer. Without this bandage fails with `Bandage: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory` and `Bandage: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory` ... I think this was the recommended approach for libraries usually provided by the host OS, but let me know if there's a way to fix this in the recipe instead.

### CODE REVIEW

**Comment by bgruening** [comment]
ok, tests are starting now

**Comment by mvdbeek** [comment]
Looks like https://github.com/bioconda/bioconda-containers/blob/main/.github/workflows/base-glibc-debian-bash.yaml#L97 requires a token now ?

**Comment by mvdbeek** [comment]
https://github.com/bioconda/bioconda-containers/pull/57 should fix that check

**Comment by mbargull** [comment]
@mvdbeek, thanks for the addition.

You've directly noticed it :smile: -- but for others stopping by: This was merged into the overall changes in gh-58 and will be available with the `quay.io/bioconda/base-glibc-debian-bash:3` images.

**Pull request closed without merging**
