### PR TITLE
run on push to main

### PR DESCRIPTION
**Pull request by daler**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @daler! And @martin-g for the review!

**Comment by martin-g** [comment]
The push to Quay.io failed with:
```
Error: trying to reuse blob sha256:174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02 at destination: checking whether a blob sha256:174f5685490326fc0a1c0f5570b8663732189b327007e47ff13d2ca59673db02 exists in ***/bioconda/bioconda-utils-build-env-cos7-x86_64: unauthorized: authentication required
```
https://github.com/bioconda/bioconda-containers/actions/runs/7540600440/job/20525545529

Could it be that the secrets are outdated ?
https://github.com/bioconda/bioconda-containers/blob/b2e3432e4fc7c2e38d3e4d62af736db1a36ea6a5/.github/workflows/build-env-image.yml#L109-L110

**Comment by martin-g** [comment]
From the same actions log:
```
Combining image name "bioconda/bioconda-utils-build-env-cos7-x86_64" and registry "***" to form registry path "***/bioconda/bioconda-utils-build-env-cos7-x86_64"
Warning: "***/bioconda/bioconda-utils-build-env-cos7-x86_64" does not seem to be a valid registry path. The registry path should not contain more than 2 slashes. Refer to the Inputs section of the readme for naming image and registry.
```
This makes me this that `${{ secrets.QUAY_BIOCONDA_REPO }}` is not just `quay.io` but something that contains a `/`, maybe `quay.io/bioconda` ?!

**Comment by daler** [comment]
I should have marked it draft, sorry! This yaml is still trying to use the Release Please release trigger used over in bioconda-utils. That's where it gets the tags from. Not sure if that's the issue here.

I don't have time to continue but @martin-g if you want to take a stab at refactoring to match the other yamls in this repo (which use major/minor versioning) that will help.

**Comment by martin-g** [comment]
Sure! I will see what has to be done!

**Pull request merged**
