### PR TITLE
Add aarch64 base images, update to Debian 12.2

### PR DESCRIPTION
**Pull request by mbargull**
- Cherry-pick changes of gh-55 for the base images.
- Update to base images to Debian 12 and BusyBox 1.36.1.
- Base BusyBox image solely on Debian base files without `docker://busybox` intermediate (to get more similar base images).
- Incorporate `libegl1` and `libopengl0` addition from gh-56.

closes gh-56

### CODE REVIEW

**Comment by mvdbeek** [comment]
Awesome, thanks so much! I noticed the push step in the CI didn't run, is this happening elsewhere @mbargull ?

**Comment by mbargull** [comment]
The base image builds got quite some overhaul with gh-55 and this PR becoming multi-platform manifests.
The Buildah/Podman build/push needed some adjustments and after https://github.com/bioconda/bioconda-containers/commit/9a47c55f80d43db3e688019f00007d68d3e785f7 and then gh-60 we now have the base images available under the `3.0` tags. (Note that they are not just yet used but only after we update `bioconda-utils`.)

**Comment by mvdbeek** [comment]
Thanks! This is mostly for multi-package-containers, we can pick a base image there.

**Comment by mbargull** [comment]
Ah, perfect! Feel free to report back if everything works as desired :).

**Pull request merged**
